compile-pdf:
  stage: build
  image: aergus/latex

  script:
    - pdflatex bericht.tex
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public
    - cd public
  artifacts:
    paths: 
      - public